import { IProfilingGroup } from 'aws-cdk-lib/aws-codeguruprofiler';
import { IVpc, SubnetSelection, ISecurityGroup } from 'aws-cdk-lib/aws-ec2';
import { PolicyStatement, IRole } from 'aws-cdk-lib/aws-iam';
import { IKey } from 'aws-cdk-lib/aws-kms';
import * as Lambda  from 'aws-cdk-lib/aws-lambda';
import { FunctionProps } from 'aws-cdk-lib/aws-lambda';
import { RetentionDays, ILogGroup } from 'aws-cdk-lib/aws-logs';
import { ITopic } from 'aws-cdk-lib/aws-sns';
import { IQueue } from 'aws-cdk-lib/aws-sqs';
import { Duration, Size } from 'aws-cdk-lib/core';
import { checkRuntime } from './checkRuntime';
import { SecMarker } from '../SecMarker';
import { checkCode, checkHandler, checkDescription } from './StandardizedNaming';

export class SecFunctionProps {
  static [SecMarker] = true;
  static defaultCode: Lambda.AssetCode = Lambda.Code.fromAsset('src')
  static defaultHandler: 'index.handler'
  runtime: Lambda.Runtime;
  code?: Lambda.Code;
  handler?: string;
  description: string;
  timeout?: Duration | undefined;
  environment?: { [key: string]: string; } | undefined;
  functionName?: string | undefined;
  memorySize?: number | undefined;
  ephemeralStorageSize?: Size | undefined;
  initialPolicy?: PolicyStatement[] | undefined;
  role?: IRole | undefined;
  vpc?: IVpc | undefined;
  ipv6AllowedForDualStack?: boolean | undefined;
  vpcSubnets?: SubnetSelection | undefined;
  securityGroups?: ISecurityGroup[] | undefined;
  allowAllOutbound?: boolean | undefined;
  allowAllIpv6Outbound?: boolean | undefined;
  deadLetterQueueEnabled?: boolean | undefined;
  deadLetterQueue?: IQueue | undefined;
  deadLetterTopic?: ITopic | undefined;
  tracing?: Lambda.Tracing | undefined;
  snapStart?: Lambda.SnapStartConf | undefined;
  profiling?: boolean | undefined;
  profilingGroup?: IProfilingGroup | undefined;
  insightsVersion?: Lambda.LambdaInsightsVersion | undefined;
  adotInstrumentation?: Lambda.AdotInstrumentationConfig | undefined;
  paramsAndSecrets?: Lambda.ParamsAndSecretsLayerVersion | undefined;
  layers?: Lambda.ILayerVersion[] | undefined;
  reservedConcurrentExecutions?: number | undefined;
  events?: Lambda.IEventSource[] | undefined;
  logRetention?: RetentionDays | undefined;
  logRetentionRole?: IRole | undefined;
  logRetentionRetryOptions?: Lambda.LogRetentionRetryOptions | undefined;
  currentVersionOptions?: Lambda.VersionOptions | undefined;
  filesystem?: Lambda.FileSystem | undefined;
  allowPublicSubnet?: boolean | undefined;
  environmentEncryption?: IKey | undefined;
  codeSigningConfig?: Lambda.ICodeSigningConfig | undefined;
  architecture?: Lambda.Architecture | undefined;
  runtimeManagementMode?: Lambda.RuntimeManagementMode | undefined;
  logGroup?: ILogGroup | undefined;
  logFormat?: string | undefined;
  loggingFormat?: Lambda.LoggingFormat | undefined;
  recursiveLoop?: Lambda.RecursiveLoop | undefined;
  applicationLogLevel?: string | undefined;
  applicationLogLevelV2?: Lambda.ApplicationLogLevel | undefined;
  systemLogLevel?: string | undefined;
  systemLogLevelV2?: Lambda.SystemLogLevel | undefined;
  onFailure?: Lambda.IDestination | undefined;
  onSuccess?: Lambda.IDestination | undefined;
  maxEventAge?: Duration | undefined;
  retryAttempts?: number | undefined;

  constructor(props: SecFunctionProps) {
    this.runtime = checkRuntime(props.runtime);
    this.code = checkCode(props.code || SecFunctionProps.defaultCode);
    this.handler = checkHandler(props.handler || SecFunctionProps.defaultHandler);
    this.description = checkDescription(props.description);
    this.timeout = props.timeout;
    this.environment = props.environment;
    this.functionName = props.functionName;
    this.memorySize = props.memorySize;
    this.ephemeralStorageSize = props.ephemeralStorageSize;
    this.initialPolicy = props.initialPolicy;
    this.role = props.role;
    this.vpc = props.vpc;
    this.ipv6AllowedForDualStack = props.ipv6AllowedForDualStack;
    this.vpcSubnets = props.vpcSubnets;
    this.securityGroups = props.securityGroups;
    this.allowAllOutbound = props.allowAllOutbound;
    this.allowAllIpv6Outbound = props.allowAllIpv6Outbound;
    this.deadLetterQueueEnabled = props.deadLetterQueueEnabled;
    this.deadLetterQueue = props.deadLetterQueue;
    this.deadLetterTopic = props.deadLetterTopic;
    this.tracing = props.tracing;
    this.snapStart = props.snapStart;
    this.profiling = props.profiling;
    this.profilingGroup = props.profilingGroup;
    this.insightsVersion = props.insightsVersion;
    this.adotInstrumentation = props.adotInstrumentation;
    this.paramsAndSecrets = props.paramsAndSecrets;
    this.layers = props.layers;
    this.reservedConcurrentExecutions = props.reservedConcurrentExecutions;
    this.events = props.events;
    this.logRetention = props.logRetention;
    this.logRetentionRole = props.logRetentionRole;
    this.logRetentionRetryOptions = props.logRetentionRetryOptions;
    this.currentVersionOptions = props.currentVersionOptions;
    this.filesystem = props.filesystem;
    this.allowPublicSubnet = props.allowPublicSubnet;
    this.environmentEncryption = props.environmentEncryption;
    this.codeSigningConfig = props.codeSigningConfig;
    this.architecture = props.architecture;
    this.runtimeManagementMode = props.runtimeManagementMode;
    this.logGroup = props.logGroup;
    this.logFormat = props.logFormat;
    this.loggingFormat = props.loggingFormat;
    this.recursiveLoop = props.recursiveLoop;
    this.applicationLogLevel = props.applicationLogLevel;
    this.applicationLogLevelV2 = props.applicationLogLevelV2;
    this.systemLogLevel = props.systemLogLevel;
    this.systemLogLevelV2 = props.systemLogLevelV2;
    this.onFailure = props.onFailure;
    this.onSuccess = props.onSuccess;
    this.maxEventAge = props.maxEventAge;
    this.retryAttempts = props.retryAttempts;
  }
}
