name: CI Pipeline

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'e2e_test/**'
      - '.github/workflows/e2e_test.yml'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'e2e_test/**'
      - '.github/workflows/e2e_test.yml'
        
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.4.0'
      - name: Install Dependencies
        run: npm install
      - name: Run ESLint
        run: npm run test

  jest:
    runs-on: ubuntu-latest
    needs: eslint
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.4.0'
      - name: Install Dependencies
        run: npm install
      - name: Run Jest Tests
        run: npm run test
