name: End-to-End Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'e2e_test/**'
      - '.github/workflows/e2e_test.yml'
  pull_request:
    paths:
      - 'e2e_test/**'
      - '.github/workflows/e2e_test.yml'
      
permissions:
  id-token: write
  contents: read

jobs:
  secure-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.4.0'

      - name: Install dependencies for E2E tests
        run: npm ci
        working-directory: e2e_test

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: eu-central-1

      - name: Install AWS CDK
        run: npm install -g aws-cdk
        
      - name: Deploy CDK Stack
        working-directory: e2e_test
        run: cdk deploy --app "npx ts-node sec-app.ts" --require-approval never
